### ISSUE TITLE
Other badges you may have missed.

### ISSUE THREAD

**Issue by Potherca** [matthiasnoback/badges#7]
In case you were not aware of it, I felt it wise to point your attention to: https://github.com/boennemann/badges

There are also more badges mentioned that have not yet reached this repository in the "pull-request" section. Might also be worth a look.

**Comment by matthiasnoback** [comment]
Thanks for pointing it out - this sort of deprecates this project (which isn't really a big problem anyway ;)).

**Comment by Potherca** [comment]
In that respect, I'm assuming you're also familiar with http://shields.io/ ?

**Comment by matthiasnoback** [comment]
Didn't know about that one either, thanks! Well, this certainly removes any reason for this library to exist, hehe.
